substitutions:
  _IMAGE_NAME_COMPONENT: upload-firestore
  _TAGNAME: v1

steps:
  - id: docker_build
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=asia.gcr.io/$PROJECT_ID/${_IMAGE_NAME_COMPONENT}:${_TAGNAME}"
      - "firestore-image"

  - id: docker_push
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/${_IMAGE_NAME_COMPONENT}:${_TAGNAME}"]
